site_name: Spectral Nexus
site_description: Spectral Nexus is a web application for data analysis, spectra classification and visualization.
site_url: https://spectral-nexus.dev
site_dir: site
site_author: Jonathan Motta
repo_url: https://github.com/jgmotta98/spectral-nexus
repo_name: jgmotta98/spectral-nexus

nav:
  - Home: index.md
  - Installation Guide: installation.md
  - Usage: usage.md
  - Database Schema: database.md

theme:
  name: material
  font:
    text: Roboto
    code: Red Hat Mono
  logo: assets/images/spectral-nexus-icon-thicker.png
  favicon: assets/images/spectral-nexus-icon-thicker.ico
  features:
    - content.code.copy
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Dark mode
      primary: deep purple
      accent: indigo

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Light mode
      primary: indigo
      accent: deep purple

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jgmotta98
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jonathan-motta/

copyright: |
  &copy; 2025 <a href="https://github.com/jgmotta98"  target="_blank" rel="noopener">Jonathan Motta</a>